### ISSUE TITLE
Can't edit project or tags of a task

### ISSUE THREAD

**Issue by HeikoAdams** [cinatic/taskwhisperer#3]
There is currently no way to modify the project and/or tags of a task

**Comment by cinatic** [comment]
the arguments are passed 1:1 to the task application so in fact you are able to add/modify the tags or project.

But the fields are not automatically added because i don't think it's very common to change tags / project. If you want to do so you can by adding tags:"your,tags". 

Customizable prefilled fields will maybe come with the settings in another version
