### ISSUE TITLE
Please update for gnome 3.38

### ISSUE THREAD

**Issue by nodens** [cinatic/taskwhisperer#77]
Hi,

Gnome 3.38 is here and some distros are shipping it now, but the extension fails with JS errors:
```
Usage of object.actor is deprecated for TaskWhispererMenuButton
get@resource:///org/gnome/shell/ui/environment.js:314:29
checkPositionInPanel@/home/nodens/.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de/extension.js:849:21
_init@/home/nodens/.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de/extension.js:742:14
enable@/home/nodens/.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de/extension.js:1024:25
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:348:26
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:222:39
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:106:13
```

Thanks for a great extension!

**Comment by jubnzv** [comment]
@nodens How did you get this stack trace? It is possible to get it on wayland?
The [lg](https://wiki.gnome.org/Projects/GnomeShell/LookingGlass) utility show me only `meta is null` error when this addon can't be started.

I am interested in fixing these compatibility issues too, and I'll try to make a patch that fixes them.

**Update:**
Answering my question... To get the additional debug information in gnome-shell 3.38.0:
* Log in to the X11 session since Wayland doesn't support session restart
* Run `sudo journalctl $(which gnome-shell) -f` in the shell
* Use `r` command in `lg` utility to restart gnome-session after changes in the addon code.

This gives me complete detailed stack traces with debug information. Sorry for this noise, I have to try it myself first.
